[package]
name = "palette"
version = "0.2.1"
edition = "2021"
license-file = "LICENSE"
description = "A simple CLI tool to visualize color palettes."

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
colored = "2.1.0"
toml = "0.8.19"
